Fix read() on files preventing exit on SIGINT
farsightsec/nmsg pull request #156
Opened 2024-08-07 20:03 UTC by kadealicious

- When IO loop breaks, its inputs now also close.
 - In do_read_file(), we poll() the input until either the input exits or we have data to read().

2024-08-08 15:15 UTC, djw1149 commented on nmsg/input_nmsg.c
> +		while(poll(&pfd, 1, NMSG_RBUF_TIMEOUT) != 1 && !input->stop)
add space between while and (

2024-08-08 15:25 UTC, djw1149 commented on nmsg/input_nmsg.c
>  do_read_file(nmsg_input_t input, ssize_t bytes_needed, ssize_t bytes_max) {
Add a comment to this function that it can be stopped asynchronously by setting the input's stop flag.

2024-08-08 15:27 UTC, djw1149 requested changes
Add a comment to do_read_file function that it can be stopped asynchronously by setting the input's stop flag.  Add space after 'while'

2024-08-28 22:17 UTC, kadealicious commented
When nmsg is built with this fix, `dnstable_convert` segfaults right before message processing finishes.  I will implement a new solution and send a message when I've made progress.

2024-10-01 16:44 UTC, shw700 approved these changes

2024-10-01 19:00 UTC, djw1149 approved these changes

2024-10-02 20:08 UTC, merged